import { Alert, Button, MenuItem, Stack, TextField, Typography } from '@mui/material'
import { List } from '@refinedev/mui'
import { useCallback, useEffect, useState } from 'react'
import { useIsSuperadmin } from '../../hooks/useIsSuperadmin'
import { supabaseClient } from '../../lib/supabase'

type Contrato = { id: string; codigo: string; version: number }
type Perfil = { id: string; nombre: string; modelo_id: string }
type Politica = { id: string; codigo: string; version: number; estado: string; limite_intentos: number; limite_segundos: number }

export function IaPoliticas() {
  const { isSuperadmin, isLoading } = useIsSuperadmin(); const [contratos, setContratos] = useState<Contrato[]>([]); const [perfiles, setPerfiles] = useState<Perfil[]>([]); const [politicas, setPoliticas] = useState<Politica[]>([]); const [codigo, setCodigo] = useState(''); const [version, setVersion] = useState(1); const [contratoId, setContratoId] = useState(''); const [principalId, setPrincipalId] = useState(''); const [fallbackId, setFallbackId] = useState(''); const [intentos, setIntentos] = useState(2); const [segundos, setSegundos] = useState(90); const [estado, setEstado] = useState('borrador'); const [error, setError] = useState<string | null>(null)
  const cargar = useCallback(async () => { const [contratosRespuesta, perfilesRespuesta, politicasRespuesta] = await Promise.all([supabaseClient.from('ia_contratos_consumidor').select('id,codigo,version').eq('estado', 'aprobado'), supabaseClient.from('ia_perfiles_modelo').select('id,nombre,modelo_id').eq('activo', true), supabaseClient.from('ia_politicas').select('id,codigo,version,estado,limite_intentos,limite_segundos').order('codigo')]); const consultaError = contratosRespuesta.error ?? perfilesRespuesta.error ?? politicasRespuesta.error; if (consultaError) setError(consultaError.message); else { setContratos((contratosRespuesta.data ?? []) as Contrato[]); setPerfiles((perfilesRespuesta.data ?? []) as Perfil[]); setPoliticas((politicasRespuesta.data ?? []) as Politica[]) } }, [])
  useEffect(() => { if (isSuperadmin) void cargar() }, [cargar, isSuperadmin])
  const guardar = async () => { setError(null); const { error: rpcError } = await supabaseClient.rpc('guardar_politica_ia', { p_codigo: codigo, p_version: version, p_contrato_id: contratoId, p_perfil_principal_id: principalId, p_perfil_fallback_id: fallbackId || null, p_limite_intentos: intentos, p_limite_segundos: segundos, p_estado: estado }); if (rpcError) setError(rpcError.message); else { setCodigo(''); await cargar() } }
  if (isLoading) return null
  if (!isSuperadmin) return <Alert severity="error" sx={{ m: 2 }}>Esta pantalla es solo para el superadmin de la plataforma.</Alert>
  return <List title="Políticas globales de IA"><Stack spacing={2}><Alert severity="info">El fallback es opcional y puede ser el mismo perfil o pertenecer a otro proveedor. Sólo se usa ante fallo técnico antes de una respuesta válida.</Alert>{error && <Alert severity="error">{error}</Alert>}<TextField label="Código" value={codigo} onChange={(event) => setCodigo(event.target.value)} /><TextField label="Versión" type="number" value={version} onChange={(event) => setVersion(Number(event.target.value))} /><TextField select label="Contrato aprobado" value={contratoId} onChange={(event) => setContratoId(event.target.value)}>{contratos.map((contrato) => <MenuItem key={contrato.id} value={contrato.id}>{`${contrato.codigo} v${contrato.version}`}</MenuItem>)}</TextField><TextField select label="Perfil principal" value={principalId} onChange={(event) => setPrincipalId(event.target.value)}>{perfiles.map((perfil) => <MenuItem key={perfil.id} value={perfil.id}>{`${perfil.nombre} · ${perfil.modelo_id}`}</MenuItem>)}</TextField><TextField select label="Perfil fallback (opcional)" value={fallbackId} onChange={(event) => setFallbackId(event.target.value)}><MenuItem value="">Sin fallback</MenuItem>{perfiles.map((perfil) => <MenuItem key={perfil.id} value={perfil.id}>{`${perfil.nombre} · ${perfil.modelo_id}`}</MenuItem>)}</TextField><TextField label="Intentos (1–2)" type="number" value={intentos} onChange={(event) => setIntentos(Number(event.target.value))} /><TextField label="Tiempo total en segundos (1–90)" type="number" value={segundos} onChange={(event) => setSegundos(Number(event.target.value))} /><TextField select label="Estado" value={estado} onChange={(event) => setEstado(event.target.value)}><MenuItem value="borrador">Borrador</MenuItem><MenuItem value="aprobada">Aprobada</MenuItem><MenuItem value="retirada">Retirada</MenuItem></TextField><Button variant="contained" disabled={!codigo || !contratoId || !principalId} onClick={() => void guardar()}>Guardar política</Button><Typography variant="h6">Políticas registradas</Typography>{politicas.map((politica) => <Typography key={politica.id}>{`${politica.codigo} v${politica.version} · ${politica.estado} · ${politica.limite_intentos} intentos / ${politica.limite_segundos}s`}</Typography>)}</Stack></List>
}
